### ISSUE TITLE
Mainnet checklist

### ISSUE THREAD

**Issue by rajkharvar** [razor-network/docs-v2#40]
- [x] Update faucet link/documentation
- [x] Update skale network config throughout docs
- [x] Update docker tag
- [ ] Update governance parameters
- [x] Update/Add new section for mainnet
- [x] Update contract addresses
- [ ] Verify delegation flow details (withdrawInitiationPeriod, unstakeLockPeriod related calculation)
